### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by acosti** [devcenter-square/android-chat-ui#10]
Hello,

I can't seem to have this work properly in RTL languages.
When I do, the button is moved to the left but its icon stays the same. Odd.

Any idea?

**Comment by timigod** [comment]
Hey, we're continuing development of this in a different repository. At least the most of us that worked on this on. You can find the new repo here https://github.com/IntentService/android-chat-ui, we haven't uploaded the new v0.1.1 to maven. But it will happen soon.

In anycase, anybody is free to continue development on this repository but most of us have moved. 

We haven't thought about RTL support just yet. But please re-add this issue to the new repo.
