### ISSUE TITLE
Version 1.0 is not yet on bintray

### ISSUE THREAD

**Issue by kranthi117** [devcenter-square/android-chat-ui#11]
The latest code is not available in any of the maven repositories

**Comment by timigod** [comment]
Hey, we're continuing development of this in a different repository. At least the most of us that worked on this on. You can find the new repo here https://github.com/IntentService/android-chat-ui, we haven't uploaded the new v0.1.1 to maven. But it will happen soon.

In anycase, anybody is free to continue development on this repository but most of us have moved.
