### ISSUE TITLE
The following classes could not be found: co.devcenter.android.ChatView

### ISSUE THREAD

**Issue by Swapnil-Garg16** [devcenter-square/android-chat-ui#5]
Following class couldn't be initiated even after adding the dependency in gradle.

**Comment by efemoney** [comment]
Sorry about that. The maven repo is still yet to be updated. This will be fixed.

**Comment by UnateD** [comment]
Error still persists. When you try to run a screen with a call chatview error occurs again

**Comment by efemoney** [comment]
@timigod Can you please update the repo. 

@UnateD Still sorry. I'll look at updating it myself.

**Comment by UnateD** [comment]
@efemoney You could write here when the error will be fixed? I liked your library in the future I would like to use it. Thx

**Comment by adilp** [comment]
Still not working

**Comment by amritsinghbains** [comment]
Not working
Didn't find class "co.devcenter.android.ChatView"

**Comment by MaroonBeret** [comment]
@efemoney I have the same problem. When do you expect this to be fixed? Can't use your lib like this

**Comment by VP2405** [comment]
co.devcenter.android.ChatView is wrong, I've tried with co.devcenter.androiduilibrary.ChatView and it works @efemoney @MaroonBeret

**Comment by rodrigo-brito** [comment]
@VP2405 That's right. Works for me!
Thank you so much!

**Comment by timigod** [comment]
Hey, we're continuing development of this in a different repository. At least the most of us that worked on this on. You can find the new repo here https://github.com/IntentService/android-chat-ui, we haven't uploaded the new v0.1.1 to maven. But it will happen soon.

In anycase, anybody is free to continue development on this repository but most of us have moved.
