### ISSUE TITLE
Open Source Licensing information missing

### ISSUE THREAD

**Issue by post2shyam** [devcenter-square/android-chat-ui#8]
Hi,

Please update the open-source licensing model for this project. It will help developers to contribute accordingly.
Thanks!

**Comment by timigod** [comment]
Hey, we're continuing development of this in a different repository. At least the most of us that worked on this on. You can find the new repo here https://github.com/IntentService/android-chat-ui, we haven't uploaded the new v0.1.1 to maven. But it will happen soon.

In any case, anybody is free to continue development on this repository but most of us have moved.
