### ISSUE TITLE
feature request --  optional button for image icon - may be video ,attachment 

### ISSUE THREAD

**Issue by madibalive** [devcenter-square/android-chat-ui#9]
Hi, i recently had to implement chat ui , as much it works good , it still require maintenance, moving to an opened source library would save me on maintenance, but the current state of this  library is very barebones , would thinking of add extra button for image upload to start things off, idea thing i should look out for ??

**Comment by sephyioth** [comment]
Dear Friends:
	I am currently using this library, just to modify a lot of aspects, such as photos, but chat-ui has modified some of the UI, it is looking forward to more improvements. In the framework of reuse and other perspectives, the improvement of chat-ui.

       Yours.
       Genesis.Ling
_________________________________
Q Q	  :286680608
Phone:18758363081
Department: Embedded Software Engineer
Send By Mac OS X

> 在 2016年9月22日，23:44，Razak Wasiu <notifications@github.com> 写道：
> 
> Hi, i recently had to implement chat ui , as much it works good , it still require maintenance, moving to an opened source library would save me on maintenance, but the current state of this library is very barebones , would thinking of add extra button for image upload to start things off, idea thing i should look out for ??

**Comment by sephyioth** [comment]
Dear Friends:
	I modified it on the basis of chatUi, plus the head, chat-ui still have a lot to do, such as: 
	1、Picture preview
	2、Small Video preview
	3、The rest of the expansion of the function 
	Step by step, the power of open source.

       Yours.
       Genesis.Ling
_________________________________
Q Q	  :286680608
Phone:18758363081
Department: Embedded Software Engineer
Send By Mac OS X

> 在 2016年9月23日，08:48，凌志 <lzrwolf@126.com> 写道：
> 
> 
> Dear Friends:
> 	I am currently using this library, just to modify a lot of aspects, such as photos, but chat-ui has modified some of the UI, it is looking forward to more improvements. In the framework of reuse and other perspectives, the improvement of chat-ui.
> 
>        Yours.
>        Genesis.Ling
> _________________________________
> Q Q	  :286680608
> Phone:18758363081
> Department: Embedded Software Engineer
> Send By Mac OS X
> 
>> 在 2016年9月22日，23:44，Razak Wasiu <notifications@github.com <mailto:notifications@github.com>> 写道：
>> 
>> Hi, i recently had to implement chat ui , as much it works good , it still require maintenance, moving to an opened source library would save me on maintenance, but the current state of this library is very barebones , would thinking of add extra button for image upload to start things off, idea thing i should look out for ??
>

**Comment by madibalive** [comment]
was hoping to hear from the OP since i dont want start pushing and have it rejected ,because it some critical parts are being affected , but would push later in the day 

- add extra button for image upload 
- add message type (text,image)

**Comment by sephyioth** [comment]
Dear Friends:
	Look forward to your project, you can read about your design style. However, image processing, then still need to pay attention to OOM, if there is a chance, you can exchange and help. I do most of the image processing class, most of the use of JNI to achieve graphics processing.

       Yours.
       Genesis.Ling
_________________________________
Q Q	  :286680608
Phone:18758363081
Department: Embedded Software Engineer
Send By Mac OS X

**Comment by timigod** [comment]
Hey, we're continuing development of this in a different repository. At least the most of us that worked on this on. You can find the new repo here https://github.com/IntentService/android-chat-ui, we haven't uploaded the new v0.1.1 to maven. But it will happen soon.

In anycase, anybody is free to continue development on this repository but most of us have moved.

We are working on image and all forms of media embeds in v0.1.2
